-- =====================================================================
-- الجداول والأعمدة والدوال اللي اتضافت في Supabase (كما هي مبنية فعلًا في الإنتاج)
-- الغرض: مرجع ونسخة استرجاع. الملف قابل للتشغيل أكتر من مرة (if not exists / or replace).
-- ملحوظة: ده لا يشمل الجداول القديمة (businesses, orders, menu_*...) اللي كانت موجودة قبل كده.
-- ملف سياسات الأمان (RLS) في ملف تاني: قاعدة-البيانات-سياسات-الأمان.sql (لسه ما اتطبقش على الإنتاج).
-- ملف حالة اتصال البوت: bot-health.sql (متطبق).
-- =====================================================================

-- ---------- أعمدة جديدة في businesses (إعدادات المطعم) ----------
alter table businesses add column if not exists feedback_enabled boolean not null default true;
alter table businesses add column if not exists feedback_delay_minutes integer not null default 180;
alter table businesses add column if not exists cart_reminder_enabled boolean not null default true;
alter table businesses add column if not exists bot_enabled boolean not null default true;

-- ---------- عمود جديد في unanswered_questions ----------
alter table unanswered_questions add column if not exists answered_by uuid;

-- ---------- جداول جديدة ----------
create table if not exists business_hours (
  id bigint generated by default as identity primary key,
  business_id uuid not null references businesses(id) on delete cascade,
  weekday smallint not null check (weekday between 0 and 6),
  is_closed boolean not null default false,
  open_time time,
  close_time time,
  sort_order int not null default 0
);
create index if not exists business_hours_biz_idx on business_hours (business_id, weekday, sort_order);

create table if not exists business_pauses (
  id bigint generated by default as identity primary key,
  business_id uuid not null references businesses(id) on delete cascade,
  scope text not null check (scope in ('orders','bot')),
  starts_at timestamptz not null default now(),
  ends_at timestamptz not null,
  reason text,
  canceled_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists business_pauses_biz_idx on business_pauses (business_id, ends_at);

create table if not exists faq_items (
  id bigint generated by default as identity primary key,
  business_id uuid not null references businesses(id) on delete cascade,
  question text not null,
  answer text not null,
  active boolean not null default true,
  sort_order int not null default 0,
  source text not null default 'manual' check (source in ('manual','customer_question')),
  source_question_id text,
  created_at timestamptz not null default now()
);
create index if not exists faq_items_biz_idx on faq_items (business_id, active, sort_order);

create table if not exists notifications (
  id bigint generated by default as identity primary key,
  business_id uuid not null references businesses(id) on delete cascade,
  type text not null,
  severity text not null default 'normal' check (severity in ('low','normal','high','urgent')),
  title text not null,
  body text,
  ref_table text,
  ref_id text,
  sender_id text,
  customer_name text,
  customer_phone text,
  requires_action boolean not null default false,
  reply_deadline timestamptz,
  status text not null default 'unread' check (status in ('unread','read','handled','dismissed')),
  created_at timestamptz not null default now(),
  read_at timestamptz,
  handled_at timestamptz
);
create index if not exists notifications_biz_idx on notifications (business_id, created_at desc);
create index if not exists notifications_unread_idx on notifications (business_id) where status = 'unread';

create table if not exists customer_replies (
  id bigint generated by default as identity primary key,
  business_id uuid not null references businesses(id) on delete cascade,
  page_id text not null,
  sender_id text not null,
  text text not null check (char_length(text) <= 1800),
  source_type text,
  source_id text,
  notification_id bigint references notifications(id) on delete set null,
  status text not null default 'pending' check (status in ('pending','sent','expired','failed')),
  sent_at timestamptz,
  error text,
  created_at timestamptz not null default now()
);
create index if not exists customer_replies_pending_idx on customer_replies (status) where status = 'pending';

create table if not exists notification_settings (
  id bigint generated by default as identity primary key,
  business_id uuid not null references businesses(id) on delete cascade,
  type text not null,
  in_app boolean not null default true,
  sound boolean not null default true,
  email boolean not null default false,
  telegram boolean not null default false,
  unique (business_id, type)
);

create table if not exists bot_health (
  business_id uuid primary key references businesses(id) on delete cascade,
  token_ok boolean,
  subscribed boolean,
  last_checked_at timestamptz,
  last_error text,
  last_customer_message_at timestamptz
);

create table if not exists business_users (
  id bigint generated by default as identity primary key,
  business_id uuid not null references businesses(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'staff' check (role in ('owner','manager','staff')),
  created_at timestamptz not null default now(),
  unique (business_id, user_id)
);

create table if not exists audit_log (
  id bigint generated by default as identity primary key,
  business_id uuid not null references businesses(id) on delete cascade,
  user_id uuid,
  action text not null,
  table_name text,
  record_id text,
  old_data jsonb,
  new_data jsonb,
  created_at timestamptz not null default now()
);
create index if not exists audit_log_biz_idx on audit_log (business_id, created_at desc);

alter table business_hours enable row level security;
alter table business_pauses enable row level security;
alter table faq_items enable row level security;
alter table notifications enable row level security;
alter table customer_replies enable row level security;
alter table notification_settings enable row level security;
alter table bot_health enable row level security;
alter table business_users enable row level security;
alter table audit_log enable row level security;

-- تحديث لحظي لصفحة الإشعارات (لو الجدول مضاف قبل كده هيطلع تنبيه "already member" وده عادي)
alter publication supabase_realtime add table notifications;

-- ---------- دالة سلات التذكير (النسخة الحالية، 20 ساعة + احترام إعدادات المطعم) ----------
create or replace function public.due_carts()
 returns table(business_id uuid, page_id text, sender_id text, items_text text, page_token text)
 language sql
 security definer
 set search_path to 'public'
as $function$
  select c.business_id, c.page_id, c.sender_id, c.items_text, b.page_token
  from pending_carts c
  join businesses b on b.id = c.business_id
  where c.status = 'open'
    and c.items_text <> ''
    and c.updated_at < now() - interval '60 minutes'
    and c.updated_at > now() - interval '20 hours'
    and b.active
    and b.bot_enabled
    and b.cart_reminder_enabled
    and coalesce(b.is_open, true)
    and (
      b.open_time is null or b.close_time is null
      or (case
            when b.close_time > b.open_time
              then (now() at time zone 'Africa/Cairo')::time between b.open_time and b.close_time
            else (now() at time zone 'Africa/Cairo')::time >= b.open_time
              or (now() at time zone 'Africa/Cairo')::time < b.close_time
          end)
    )
    and not exists (
      select 1 from bot_pauses p
      where p.page_id = c.page_id and p.sender_id = c.sender_id
        and p.paused_at > now() - make_interval(mins => coalesce(b.human_pause_minutes, 60))
    )
    and not exists (
      select 1 from orders o
      where o.business_id = c.business_id and o.sender_id = c.sender_id
        and o.created_at > c.updated_at - interval '5 minutes'
    )
  limit 50;
$function$;

-- ---------- دالة الردود المعلّقة (لـ workflow "إرسال الردود") ----------
create or replace function public.pending_replies()
returns table(id bigint, business_id uuid, page_id text, sender_id text, text text, page_token text, last_msg timestamptz)
language sql
security definer
set search_path to 'public'
as $function$
  select r.id, r.business_id, r.page_id, r.sender_id, r.text, b.page_token,
         (select max(m.created_at) from message_log m where m.page_id = r.page_id and m.sender_id = r.sender_id) as last_msg
  from customer_replies r
  join businesses b on b.id = r.business_id
  where r.status = 'pending' and b.active
  order by r.id
  limit 20;
$function$;

-- ---------- قفل الدوال الداخلية عن المتصفح (إصلاح ثغرة تسريب page_token) ----------
revoke execute on function public.due_carts() from public, anon, authenticated;
revoke execute on function public.pending_replies() from public, anon, authenticated;
grant execute on function public.due_carts() to service_role;
grant execute on function public.pending_replies() to service_role;
